baseURL = "https://ziravocado.github.io/"
defaultContentLanguage = "id"

paginate = 10

buildDrafts = false
buildFuture = false

googleAnalytics = "G-8KBRJ1X5KN"

[imaging]
  anchor = 'Center'

[taxonomies]
  author = "authors"
  tag = "tags"

[sitemap]
  filename = "sitemap.xml"
  changefreq = "daily"
  priority = 0.5

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[related]
  threshold = 1
	includeNewer = true
	toLower = true

[[related.indices]]
  name = "authors"
  weight = 100

[[related.indices]]
  name = "tags"
  weight = 75

[[related.indices]]
  name = "date"
  weight = 10

[[related.indices]]
  applyFilter = true
  name = 'fragmentrefs'
  type = 'fragments'
  weight = 10
