colorScheme = "noir"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

disableImageOptimization = false
disableTextInHeader = false

defaultBackgroundImage = "/imgs/background.jpg"
defaultFeaturedImage = "/imgs/background.jpg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed-gradient"

[homepage]
  layout = "background"
  homepageImage = "/imgs/background.jpg"
  showRecent = false
  showRecentItems = 1
  showMoreLink = false
  # showMoreLinkDest = "/"
  cardView = true
  cardViewScreenWidth = true
  layoutBackgroundBlur = true

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = false

[article]
  showDate = true
  showViews = true
  showLikes = true
  showComments = false
  showDateOnlyInArticle = false
  showDateUpdated = true
  showAuthor = false
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = ""
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = false
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = false
  relatedContentLimit = 1
  showTaxonomies = true
  showAuthorsBadges = false
  showWordCount = true
  sharingLinks = [ "email", "facebook", "pinterest", "telegram", "whatsapp", "x-twitter" ]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showSummary = true
  showViews = false
  showLikes = false
  showComments = false
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = true
  constrainItemsWidth = true

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

[term]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = true

[sitemap]
  excludedKinds = []

[verification]
  google = "XwiuNOh9ibj8Ho3y-od5o85IusGF7ZcxUZgnIyeJ9Ao"

[firebase]
  apiKey = "AIzaSyC0rapWjt-t-HgOBJZyLBz0JkzbyDXIElI"
  authDomain = "ziravocado-site.firebaseapp.com"
  projectId = "ziravocado-site"
  storageBucket = "ziravocado-site.appspot.com"
  messagingSenderId = "362986214736"
  appId = "1:362986214736:web:391753033374701fbac855"
  measurementId = "G-8KBRJ1X5KN"
